//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCayXanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int BuyID { get; set; }
        public int GreeneryID { get; set; }
        public string Provider { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public int Price { get; set; }
        public string Image { get; set; }
    
        public virtual Greenery Greenery { get; set; }
    }
}
